use_frameworks!
platform :ios, '12.0'

target 'WristcoinPOS_Example' do
  pod 'WristcoinPOS', :path => '../'

  target 'WristcoinPOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble'
  end
end
